version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AVNS_xakSZmrh84fL7tKvWbo
      MYSQL_DATABASE: defaultdb
    ports:
      - '3306:3306'
